### ISSUE TITLE
`:read` phase exceptions are written with previous group id

### ISSUE THREAD

**Issue by volrath** [Unrepl/unrepl#23]
Easier to explain with an example, let's say `<-` represents user input, and `->` unrepl output

```
-> [:hello ...]
-> [:prompt ...]
<- 'something
-> [:read ... 1] [:started-eval ... 1] [:eval ... 1]

-> [:prompt ...]
<- /not-a-valid-input
-> [:exception ... 1]
-> [:read ... nil]

-> [:prompt ...]
```

So, this exception comes associated with group-id 1, which shouldn't be true.  The root of the problem is that `eval-id` gets incremented on reads, but here the exception happens on the `:read` phase.

My initial thought on solving this is:

```clj
             :caught (fn [e]
                       (ensure-unrepl)
                       (let [{:keys [::ex ::phase]
                              :or {ex e phase :repl}} (ex-data e)]
                         (write [:exception {:ex ex :phase phase} (if (= phase :read) <inc eval-id or nil> @eval-id)])))
```

But I don't know if...
1. this is the best approach.
2. we want to make these exceptions have `nil` eval id, or just increment it.

thoughts?

**Comment by volrath** [comment]
thanks!

**Comment by cgrand** [comment]
You're welcome! I hope you didn't relied on evals having consecutive ids.

**Comment by volrath** [comment]
I am, particularly for this feature: https://github.com/Unrepl/unrepl.el/blob/master/gifs/grouped-outs.gif

I assoc history entries to group ids, and when an `:out` or `:err` message comes that seems out of place, I place it with its corresponding history-entry/group-id prompt.  I was actually doing the same with exceptions (unaware) and that's how I found out about this.

**Comment by cgrand** [comment]
I don't understand how having holes in the eval-id sequence is problematic. Don't you use a hashtable to map ids to whatever info you need?

**Comment by volrath** [comment]
Having holes in the sequence is not a problem, having messages with wrong group ids is. In the case of the issue I reported, the exception came with a group id that belongs to a previous read/eval.  I don't mind if group ids are not incremental uuids or nil in some cases, just as long as this type of thing don't happen.
