### ISSUE TITLE
How to handle unparseable keywords?

### ISSUE THREAD

**Issue by mauricioszabo** [Unrepl/unrepl#48]
In Clojure, we can eval `(keyword "foo" "bar")` and this will give us the result `:foo bar`. Problem is that clojure's EDN reader doesn't agrees that this is a valid keyword!

So, if we evaluate: `{(keyword "foo" "bar") 10}`, the resulting map will be `{:foo bar 10}`. UNREPL will give us a result: `[:eval {:foo bar 10} 1]`.

What's the expected way to read this result? What's the workaround?

**Comment by cgrand** [comment]
Hi, thanks for pointing out this omission! The answer is to introduce a new tagged literal `#unrepl/bad-keyword ["ns" "name"]`. Same with bad symbols.
